package repaso2tri_pspruben;

import java.io.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ruben
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    File f, sha;
    MessageDigest md=null;
    String cad, aux, volcado;
    FileReader file1;
    BufferedReader buffRead;
    FileWriter file2;
    BufferedWriter buffWriter;

    
    /**
     * Creates new form Principal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngroup_red = new javax.swing.ButtonGroup();
        text_rutaArchivo = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        label_archivo = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_rutaArchivo.setEditable(false);
        text_rutaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_rutaArchivoActionPerformed(evt);
            }
        });

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        label_archivo.setText("Ruta del Archivo:");

        btn_enviar.setText("ENVIAR");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_archivo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_rutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_buscar)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label_archivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_rutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviar)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        
       Buscador buscador = new Buscador();    
       JFileChooser fc=new JFileChooser();
       
       fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Creamos el filtro
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");
        //Le indicamos el filtro
        fc.setFileFilter(filtro);
       
       //guardamos la seleccion de fichero
       int seleccion=fc.showOpenDialog(buscador);
       
       if(seleccion==JFileChooser.APPROVE_OPTION){

	//Seleccionamos el fichero
	File fichero=fc.getSelectedFile();

	//Ecribe la ruta del fichero seleccionado en el campo de texto
	text_rutaArchivo.setText(fichero.getAbsolutePath());
        
        f= new File(fichero.getAbsoluteFile().toString());
        
            if(!f.exists()){
                try {
                    f.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
         System.out.println("Fichero seleccionado");
       
       }
       
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
        try{
           
        //cogemos la linea que tiene el fichero y la guardamos 
        file1 = new FileReader(f);
        buffRead = new BufferedReader(file1);
        
        while((volcado=buffRead.readLine())!=null){
                aux=volcado;
                System.out.println("cadena = "+aux);
        }

        
        //Pasamos el texto a bytes y lo guardamos en un array de bytes
         md= MessageDigest.getInstance("SHA-512");
         md.update(aux.getBytes());
         byte[] cifrado =md.digest();
         
         //Pasamos a base64 para visualizar el aray de bytes
         Base64.Encoder codi= Base64.getEncoder();
         String ba= codi.encodeToString(cifrado);
         
         //lo pasamos a hexadecimal
         for(byte sos: cifrado){
             int b= sos & 0xff;
             if(Integer.toHexString(b).length() == 1){
                 cad += Integer.toHexString(b);
             }
         }
         System.out.println("Hexadecimal: " + cad);
         System.out.println("Cifrando Fichero seleccionado...");

         
         //Generamos el archivo .sha512 y guardamos el valor dentro
         sha= new File("uno.txt.sha512");
        
        try {
            if(!sha.exists()){           
                    sha.createNewFile();  
            }
            System.out.println("Escribiendo el cifrado del fichero");

             file2 = new FileWriter(sha);
             buffWriter = new BufferedWriter(file2);
            buffWriter.write(cad+"\tuno.txt");
            
            file2.flush();
             System.out.println("Proceso finalizado!!!");

            
            
            
         } catch (IOException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }    
        
        }catch(NoSuchAlgorithmException e){
            System.out.println("Error algoritmo SHA-512 no disponible");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        /*try {
            //cerramos en orden todo los ficheros abiertos
            buffWriter.close();
            buffRead.close();
            file2.flush();
            file2.close();
            file1.close();
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }*/

        
           

        
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void text_rutaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_rutaArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_rutaArchivoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JLabel label_archivo;
    private javax.swing.ButtonGroup rbtngroup_red;
    private javax.swing.JTextField text_rutaArchivo;
    // End of variables declaration//GEN-END:variables
}
