/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cifrar_descifrar;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class VentanaCD extends javax.swing.JFrame {

    private JFileChooser jFC_fichero;
    private File fichero;
    private Cifrado cf;
    
    
    /**
     * Creates new form VentanaCD
     */
    public VentanaCD() {
        initComponents();
        jFC_fichero = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_rutaArchivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_rutaPass = new javax.swing.JTextField();
        btn_abrir = new javax.swing.JButton();
        rbtn_cifrar = new javax.swing.JRadioButton();
        rbtn_descifrar = new javax.swing.JRadioButton();
        btn_enviar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivo");

        txt_rutaArchivo.setEditable(false);
        txt_rutaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutaArchivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Pass:");

        txt_rutaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutaPassActionPerformed(evt);
            }
        });

        btn_abrir.setText("Abrir");
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_cifrar);
        rbtn_cifrar.setText("Cifrar");
        rbtn_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_cifrarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_descifrar);
        rbtn_descifrar.setText("Descifrar");

        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rutaPass, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txt_rutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(btn_abrir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_cifrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtn_descifrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_enviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_salir)
                                .addGap(38, 38, 38)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_rutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_rutaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_cifrar)
                    .addComponent(rbtn_descifrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviar)
                    .addComponent(btn_salir))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rutaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutaArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutaArchivoActionPerformed

    private void txt_rutaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutaPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutaPassActionPerformed

    private void rbtn_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_cifrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_cifrarActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        // TODO add your handling code here:
         int valor = jFC_fichero.showOpenDialog(this);
        if(valor == JFileChooser.APPROVE_OPTION){
            fichero = jFC_fichero.getSelectedFile();
            txt_rutaArchivo.setText(fichero.getPath());
        }

    }//GEN-LAST:event_btn_abrirActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        // TODO add your handling code here:
         String ruta = txt_rutaArchivo.getText().trim();
        if (ruta.length() == 0){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un archivo.");
            return;
        }
        String pass = txt_rutaPass.getText().trim();
        if (pass.length() == 0){
            JOptionPane.showMessageDialog(this, "Debe introducir una contraseña.");
            return;
        }
        cf = new Cifrado(fichero, pass);
        
        if (rbtn_cifrar.isSelected()){
            cf.Codifica();
            JOptionPane.showMessageDialog(this, "Fichero "+fichero.getPath()+" cifrado con exito.");
        }
       if (rbtn_descifrar.isSelected()){
            cf.Descodifica();
            JOptionPane.showMessageDialog(this, "Fichero "+fichero.getPath()+" descifrado con exito.");
        }
        
        
        limpiar();

    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed


   private void limpiar() {
        txt_rutaArchivo.setText("");
       txt_rutaPass.setText("");
       rbtn_cifrar.setSelected(true);
       rbtn_descifrar.setSelected(false);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtn_cifrar;
    private javax.swing.JRadioButton rbtn_descifrar;
    private javax.swing.JTextField txt_rutaArchivo;
    private javax.swing.JTextField txt_rutaPass;
    // End of variables declaration//GEN-END:variables
}
